services:
  flask:
    build: ./flask
    container_name: flask
    ports:
      - "5000:5000"
    environment:
      MONGODB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGODB_USERNAME: ${MONGO_USERNAME}
      MONGODB_PASSWORD: ${MONGO_PASSWORD}
      MONGODB_HOSTNAME: mongodb
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
    depends_on:
      - mongodb
    volumes:
      - ./flask/blog:/app/blog
    networks:
      - backend

  mongodb:
    image: mongo:4.4.3
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
      - "./mongodb/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local



